app:
  env: "development"
  port: 4000
  debug: true

mysql:
  username: "admin"
  password: "admin1234"
  host: "localhost"
  port: 3306
  dbname: product

redis:
  username: "default"
  password: "redispw"
  address: "localhost:55001"
  db: 0

log:
  level: 1 # 1=debug, 2=info
  format: "json"